# OpenDartReader - Users Guide

<img width="40%" src="https://i.imgur.com/FMsL0id.png" >

`OpenDartReader`는 금융감독원 전자공시 시스템의 "Open DART"서비스 API를 손쉽게 사용할 수 있도록 돕는 오픈소스 라이브러리 입니다.

#### 2020-2021 [FinanceData.KR](http://financedata.kr) | [facebook.com/financedata](http://facebook.com/financedata)

##  OpenDartReader
`Open DART`는 금융감독원이 제공하는 전자공시 시스템에서 제공하는 API서비스 입니다. 기존의 "오픈API", "공시정보 활용마당" 서비스 확대개편하였으며 2020-01-21 (시범) 서비스 시작하였습니다.

`Open DART` API는 매우 잘 만들어진 서비스입니다. 하지만, API를 직접사용하면 추가적인 작업들이 필요합니다. 예를 들어, `Open DART` API는 기업에 대한 내용을 조회할 때, 전자공시에서 사용하는 개별 기업의 고유 번호를 사용합니다. 특정 회사를 상장회사 종목코드으로 조회하려면 매번 고유번호를 얻어야 합니다. 수신한 데이터는 JSON혹은 XML형태 인데 대부분의 경우 pandas 데이터프레임(DataFrame)으로 가공해야 사용하기 더 편리합니다.

`OpenDartReader`는 `Open DART`를 이런 내용을 일반화하고 좀 더 쉽게 `Open DART`를 사용하기 위한 파이썬 라이브러리 입니다.

## Installation

다음과 같이 설치 합니다.

```bash
pip install opendartreader
```

이미 설치되어 있고 업그레이드가 필요하다면 다음과 같이 설치합니다.
```bash
pip install --upgrade opendartreader 
```

## Quick Start

```python
import OpenDartReader

# ==== 0. 객체 생성 ====
# 객체 생성 (API KEY 지정) 
api_key = ''
dart = OpenDartReader(api_key) 


# == 1. 공시정보 검색 ==
# 삼성전자 2019-07-01 하루 동안 공시 목록 (날짜에 다양한 포맷이 가능합니다)
dart.list('005930', end='2019-7-1')

# 삼성전자 상장이후 모든 공시 목록 (5,142 건+)
dart.list('005930', start='1900') 

# 삼성전자 2010-01-01 ~ 2019-12-31 모든 공시 목록 (2,676 건)
dart.list('005930', start='2010-01-01', end='2019-12-31') 

# 삼성전자 1999-01-01 이후 모든 정기보고서
dart.list('005930', start='1999-01-01', kind='A', final=False)

# 삼성전자 1999년~2019년 모든 정기보고서(최종보고서)
dart.list('005930', start='1999-01-01', end='2019-12-31', kind='A') 


# 2020-07-01 하루동안 모든 공시목록
dart.list(end='20200701')

# 2020-01-01 ~ 2020-01-10 모든 회사의 모든 공시목록 (4,209 건)
dart.list(start='2020-01-01', end='2020-01-10')

# 2020-01-01 ~ 2020-01-10 모든 회사의 모든 공시목록 (정정된 공시포함) (4,876 건)
dart.list(start='2020-01-01', end='2020-01-10', final=False)

# 2020-07-01 부터 현재까지 모든 회사의 정기보고서
dart.list(start='2020-07-01', kind='A')

# 2019-01-01 ~ 2019-03-31 모든 회사의 정기보고서 (961건)
dart.list(start='20190101', end='20190331', kind='A')


# 기업의 개황정보
dart.company('005930')

# 회사명에 삼성전자가 포함된 회사들에 대한 개황정보
dart.company_by_name('삼성전자')

# 삼성전자 사업보고서 (2018.12) 원문 텍스트
xml_text = dart.document('20190401004781')


# ==== 2. 사업보고서 ====
# 삼성전자(005930), 배당관련 사항, 2018년
dart.report('005930', '배당', 2018) 

# 서울반도체(046890), 최대주주 관한 사항, 2018년
dart.report('046890', '최대주주', 2018) 

# 서울반도체(046890), 임원 관한 사항, 2018년
dart.report('046890', '임원', 2018) 

# 삼성바이오로직스(207940), 2019년, 소액주주에 관한 사항
dart.report('207940', '소액주주', '2019')


# ==== 3. 상장기업 재무정보 ====
# 삼성전자 2018 재무제표 
dart.finstate('삼성전자', 2018) # 사업보고서

# 삼성전자 2018Q1 재무제표
dart.finstate('삼성전자', 2018, reprt_code='11013')

# 여러종목 한번에
dart.finstate('00126380,00164779,00164742', 2018)
dart.finstate('005930, 000660, 005380', 2018)
dart.finstate('삼성전자, SK하이닉스, 현대자동차', 2018)

# 단일기업 전체 재무제표 (삼성전자 2018 전체 재무제표)
dart.finstate_all('005930', 2018)

# 재무제표 XBRL 원본 파일 저장 (삼성전자 2018 사업보고서)
dart.finstate_xml('20190401004781', save_as='삼성전자_2018_사업보고서_XBRL.zip')

# XBRL 표준계정과목체계(계정과목)
dart.xbrl_taxonomy('BS1')


# ==== 4. 지분공시 ====
# 대량보유 상황보고 (종목코드, 종목명, 고유번호 모두 지정 가능)
dart.major_shareholders('삼성전자')

# 임원ㆍ주요주주 소유보고 (종목코드, 종목명, 고유번호 모두 지정 가능)
dart.major_shareholders_exec('005930')


# ==== 5. 확장 기능 ====
# 지정한 날짜의 공시목록 전체 (시간 정보 포함)
dart.list_date_ex('2020-01-03')

# 개별 문서 제목과 URL
rcp_no = '20190401004781' # 삼성전자 2018년 사업보고서
dart.sub_docs(rcp_no)

# 제목이 잘 매치되는 순서로 소트
dart.sub_docs('20190401004781', match='사업의 내용')

# 첨부 문서 제목과 URL
dart.attach_doc_list(rcp_no)

# 제목이 잘 매치되는 순서로 소트
dart.attach_doc_list(rcp_no, match='감사보고서')

# 첨부 파일 제목과 URL
dart.attach_file_list(rcp_no)
```

## 0. OpenDartReader 객체 dart를 생성

가장 먼저 해야할 일은 발급 받은 API키를 사용하여 `OpenDartReader` 객체를 생성하는 것입니다. 

API키는 전자공시 [인증키 신청 페이지](https://opendart.fss.or.kr/uss/umt/EgovMberInsertView.do)에서 회원가입하고 신청하면 바로 발급 받을 수 있습니다. API키는 40자의 영문과 숫자로 구성되어 있습니다.

In [4]:
import OpenDartReader

api_key = ''

dart = OpenDartReader(api_key)

## 1. 공시정보 검색

### list() - 공시검색  (개별종목)
지정한 회사의 보고서를 검색합니다. 기간과 보고서의 종류를 지정할 수 있습니다.

```python
dart.list(corp, start=None, end=None, kind='', kind_detail='', final=True)
```

#### 날짜 지정하는 방법
`start`와 `end`에 지정하는 날짜의 형식 '2020-07-01', '2020-7-1', '20200701', '1 july 2020', 'JULY 1 2020' 모두 가능합니다. datetime객체도 가능합니다.

* start 와 end를 함께 지정하면 start~end 기간을 지정합니다.
* start만 지정하면 start 부터 현재까지,
* end만 지정하면 end 하루를 지정하게 됩니다.

In [2]:
# 삼성전자 2019-07-01 하루 동안 공시 목록
dart.list('005930', end='2019-7-1')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20190701000283,안규리,20190701,

In [3]:
# 삼성전자 상장이후 모든 공시 목록 (5,142 건+)
dart.list('005930', start='1900')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20210111000382,안규리,20210111,
1,00126380,삼성전자,005930,Y,최대주주등소유주식변동신고서,20210108800652,삼성전자,20210108,유
2,00126380,삼성전자,005930,Y,기업설명회(IR)개최(안내공시),20210108800573,삼성전자,20210108,유
3,00126380,삼성전자,005930,Y,연결재무제표기준영업(잠정)실적(공정공시),20210108800029,삼성전자,20210108,유
4,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20210107000257,국민연금공단,20210107,
...,...,...,...,...,...,...,...,...,...
36,00126380,삼성전자,005930,Y,채무보증(담보제공포함),20000404000429,삼성전자,20000404,
37,00126380,삼성전자,005930,Y,최대주주등을위한금전의대여,20000401000031,삼성전자,20000401,
38,00126380,삼성전자,005930,Y,감사보고서 (1999.12),20000320000124,삼일회계법인,20000320,
39,00126380,삼성전자,005930,Y,[기재정정]반기보고서 (1999.06),19990824000003,삼성전자,19990824,
40,00126380,삼성전자,005930,Y,[기재정정]사업보고서 (1998.12),19990626000007,삼성전자,19990626,연

In [4]:
# 삼성전자 2010-01-01 ~ 2019-12-31 모든 공시 목록 (2,676 건)
dart.list('005930', start='2010-01-01', end='2019-12-31')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20191231000470,유병길,20191231,
1,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20191231000412,성인희,20191231,
2,00126380,삼성전자,005930,Y,[기재정정]임원ㆍ주요주주특정증권등소유상황보고서,20191231000215,전준영,20191231,
3,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20191230000401,이상훈,20191230,
4,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20191230000200,이원진,20191230,
...,...,...,...,...,...,...,...,...,...
6,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20100104000135,이상완,20100104,
7,00126380,삼성전자,005930,Y,[기재정정]임원ㆍ주요주주특정증권등소유상황보고서,20100104000127,유두영,20100104,
8,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20100104000105,전준영,20100104,
9,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20100104000060,최광수,20100104,
10,00126380,삼성전자,005930,Y,임원ㆍ주요주주특정증권등소유상황보고서,20100104000022,방상원,20100104,

In [5]:
# 삼성전자 1999-01-01 이후 모든 정기보고서 (85건)
dart.list('005930', start='1999-01-01', kind='A')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,분기보고서 (2020.09),20201116001248,삼성전자,20201116,
1,00126380,삼성전자,005930,Y,반기보고서 (2020.06),20200814001766,삼성전자,20200814,
2,00126380,삼성전자,005930,Y,분기보고서 (2020.03),20200515001451,삼성전자,20200515,
3,00126380,삼성전자,005930,Y,사업보고서 (2019.12),20200330003851,삼성전자,20200330,연
4,00126380,삼성전자,005930,Y,분기보고서 (2019.09),20191114001273,삼성전자,20191114,
...,...,...,...,...,...,...,...,...,...
81,00126380,삼성전자,005930,Y,반기보고서 (2000.06),20000814000482,삼성전자,20000814,
82,00126380,삼성전자,005930,Y,[첨부추가]사업보고서 (1999.12),20000330000796,삼성전자,20000330,연
83,00126380,삼성전자,005930,Y,분기보고서 (2000.03),20000515000739,삼성전자,20000515,
84,00126380,삼성전자,005930,Y,[기재정정]반기보고서 (1999.06),19990824000003,삼성전자,19990824,
85,00126380,삼성전자,005930,Y,[기재정정]사업보고서 (1998.12),19990626000007,삼성전자,19990626,연

In [6]:
# 삼성전자 1999년~2019년 모든 정기보고서(최종보고서) (82건)
dart.list('005930', start='1999-01-01', end='2019-12-31', kind='A', final=False)

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126380,삼성전자,005930,Y,분기보고서 (2019.09),20191114001273,삼성전자,20191114,
1,00126380,삼성전자,005930,Y,반기보고서 (2019.06),20190814002218,삼성전자,20190814,
2,00126380,삼성전자,005930,Y,분기보고서 (2019.03),20190515001605,삼성전자,20190515,
3,00126380,삼성전자,005930,Y,사업보고서 (2018.12),20190401004781,삼성전자,20190401,연
4,00126380,삼성전자,005930,Y,분기보고서 (2018.09),20181114001530,삼성전자,20181114,
...,...,...,...,...,...,...,...,...,...
82,00126380,삼성전자,005930,Y,분기보고서 (2000.03),20000515000739,삼성전자,20000515,
83,00126380,삼성전자,005930,Y,[기재정정]반기보고서 (1999.06),19990824000003,삼성전자,19990824,
84,00126380,삼성전자,005930,Y,반기보고서 (1999.06),19990814000182,삼성전자,19990814,정
85,00126380,삼성전자,005930,Y,[기재정정]사업보고서 (1998.12),19990626000007,삼성전자,19990626,연
86,00126380,삼성전자,005930,Y,사업보고서 (1998.12),19990403000009,삼성전자,19990403,정연

### list() - 공시검색 (모든종목)
회사(종목)를 지정하지 않으면 모든 종목에 대한 공시를 검색합니다. (이때, 검색 기간은 `start` 와 `end` 사이의 3개월 이내 범위만 가능합니다). 주로 모든 회사를 대상으로 최근 공시를 조회할 목적으로 사용합니다

In [7]:
# 2020-07-01 하루동안 모든 공시목록
dart.list(end='20200701')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00260453,삼성자산운용,,E,일괄신고서(집합투자증권-신탁형)(삼성연타남녀4050증권자투자신탁H[채권혼합-재간접형]),20200701000036,삼성자산운용,20200701,
1,00260453,삼성자산운용,,E,일괄신고서(집합투자증권-신탁형)(삼성연타남녀3040증권자투자신탁H[주식혼합-재간접형]),20200701000053,삼성자산운용,20200701,
2,00260453,삼성자산운용,,E,일괄신고서(집합투자증권-신탁형)(삼성연타남녀2030증권자투자신탁H[주식혼합-재간접형]),20200701000056,삼성자산운용,20200701,
3,00260453,삼성자산운용,,E,[기재정정]증권신고서(집합투자증권-신탁형)(삼성지수연계증권투자신탁11호[ELS-파생형]),20200701000453,삼성자산운용,20200701,
4,00260453,삼성자산운용,,E,[기재정정]일괄신고서(집합투자증권-신탁형)(삼성평생소득TIF40증권자투자신탁H[채권...,20200701000164,삼성자산운용,20200701,
...,...,...,...,...,...,...,...,...,...
20,00326272,하나유비에스자산운용,,E,효력발생안내( 2020.6.25. 제출 증권신고서(집합투자증권-신탁형) ),20200630100014,금융감독원,20200701,
21,00326272,하나유비에스자산운용,,E,효력발생안내( 2020.6.25. 제출 일괄신고서(집합투자증권-신탁형) ),20200630100013,금융감독원,20200701,
22,00326272,하나유비에스자산운용,,E,효력발생안내( 2020.6.25. 제출 증권신고서(집합투자증권-신탁형) ),20200630100012,금융감독원,20200701,
23,00326272,하나유비에스자산운용,,E,효력발생안내( 2020.6.25. 제출 증권신고서(집합투자증권-신탁형) ),20200630100011,금융감독원,20200701,
24,00326272,하나유비에스자산운용,,E,효력발생안내( 2020.6.25. 제출 증권신고서(집합투자증권-신탁형) ),20200630100010,금융감독원,20200701,

In [8]:
# 2020-01-01 ~ 2020-01-10 모든 회사의 모든 공시목록
dart.list(start='2020-01-01', end='2020-01-10')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합사채-주가연계파생결합사채),20200110000372,NH투자증권,20200110,
1,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합사채-주가연계파생결합사채),20200110000323,NH투자증권,20200110,
2,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합사채-주가연계파생결합사채),20200108000401,NH투자증권,20200108,
3,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합증권-주가연계증권),20200110000678,NH투자증권,20200110,
4,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합증권-주가연계증권),20200110000534,NH투자증권,20200110,
...,...,...,...,...,...,...,...,...,...
5,00111722,미래에셋대우,006800,Y,증권발행실적보고서,20191231000542,미래에셋대우,20200102,
6,00425962,삼성화재서비스손해사정,,E,동일인등출자계열회사와의상품ㆍ용역거래,20191231000543,삼성화재서비스손해사정,20200102,공
7,01236815,선산,,E,[기재정정]주요사항보고서(회사합병결정),20191231000541,선산,20200102,
8,00442233,한국산업양행,,E,연결감사보고서 (2018.12),20191231000540,회계법인세진,20200102,
9,00160144,한국투자증권,,E,증권발행실적보고서,20191231000538,한국투자증권,20200102,

In [9]:
# 2020-01-01 ~ 2020-01-10 모든 회사의 모든 공시목록 (정정된 공시포함)
dart.list(start='2020-01-01', end='2020-01-10', final=False)

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00146427,일야,058450,K,[첨부추가]주요사항보고서(타법인주식및출자증권양수결정),20200110000851,일야,20200110,정
1,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합사채-주가연계파생결합사채),20200110000372,NH투자증권,20200110,
2,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합사채-주가연계파생결합사채),20200110000323,NH투자증권,20200110,
3,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합사채-주가연계파생결합사채),20200108000401,NH투자증권,20200108,
4,00120182,NH투자증권,005940,Y,[첨부추가]일괄신고추가서류(파생결합증권-주가연계증권),20200110000678,NH투자증권,20200110,
...,...,...,...,...,...,...,...,...,...
71,00111722,미래에셋대우,006800,Y,증권발행실적보고서,20191231000542,미래에셋대우,20200102,
72,00425962,삼성화재서비스손해사정,,E,동일인등출자계열회사와의상품ㆍ용역거래,20191231000543,삼성화재서비스손해사정,20200102,공
73,01236815,선산,,E,[기재정정]주요사항보고서(회사합병결정),20191231000541,선산,20200102,
74,00442233,한국산업양행,,E,연결감사보고서 (2018.12),20191231000540,회계법인세진,20200102,
75,00160144,한국투자증권,,E,증권발행실적보고서,20191231000538,한국투자증권,20200102,

In [10]:
# 2021-01-01 부터 현재까지 모든 회사의 정기보고서
dart.list(start='2021-01-01', kind='A')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,01133466,멈스,,E,반기보고서 (2020.06),20210112000228,멈스,20210112,
1,00197759,미래산업,025560,Y,[기재정정]사업보고서 (2019.12),20210111000674,미래산업,20210111,연
2,01133466,멈스,,E,분기보고서 (2020.03),20210111000606,멈스,20210111,
3,00618401,크루셜텍,114120,K,[기재정정]분기보고서 (2020.09),20210111000504,크루셜텍,20210111,
4,00808086,애니젠,196300,K,[기재정정]분기보고서 (2020.09),20210108000778,애니젠,20210108,
5,01013694,인카금융서비스,211050,N,[기재정정]사업보고서 (2019.12),20210108000667,인카금융서비스,20210108,연
6,01013694,인카금융서비스,211050,N,[기재정정]사업보고서 (2018.12),20210108000631,인카금융서비스,20210108,
7,01343920,유안타제4호스팩,313750,K,[기재정정]분기보고서 (2020.09),20210108000017,유안타제4호스팩,20210108,
8,01343920,유안타제4호스팩,313750,K,[기재정정]반기보고서 (2020.06),20210108000016,유안타제4호스팩,20210108,
9,01343920,유안타제4호스팩,313750,K,[기재정정]분기보고서 (2020.03),20210108000015,유안타제4호스팩,20210108,
10,00567222,우림기계,101170,K,[기재정정]분기보고서 (2020.09),20210107000344,우림기계,20210107,
11,00814786,스카이이앤엠,131100,K,[기재정정]분기보고서 (2020.09),20210106000409,스카이이앤엠,20210106,
12,01267602,유안타제3호스팩,287410,K,[기재정정]분기보고서 (2020.09),20210104000376,유안타제3호스팩,20210104,
13,01267602,유안타제3호스팩,287410,K,[기재정정]반기보고서 (2020.06),20210104000364,유안타제3호스팩,20210104,
14,01267602,유안타제3호스팩,287410,K,[기재정정]분기보고서 (2020.03),20210104000357,유안타제3호스팩,20210104,
15,01267602,유안타제3호스팩,287410,K,[기재정정]사업보고서 (2019.12),20210104000351,유안타제3호스팩,20210104,
16,01267602,유안타제3호스팩,287410,K,[기재정정]분기보고서 (2019.09),20210104000343,유안타제3호스팩,20210104,
17,01267602,유안타제3호스팩,287410,K,[기재정정]반기보고서 (2019.06),20210104000326,유안타제3호스팩,20210104,
18,01267602,유안타제3호스팩,287410,K,[기재정정]분기보고서 (2019.03),20210104000297,유안타제3호스팩,20210104,

In [11]:
# 2019-01-01 ~ 2019-03-31 모든 회사의 정기보고서
dart.list(start='20190101', end='20190331', kind='A')

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00151447,천지산업,001490,E,[첨부추가]사업보고서 (2018.12),20190329000292,천지산업,20190329,연
1,00155498,풍림산업,001310,E,[첨부추가]사업보고서 (2018.12),20190329003400,풍림산업,20190329,연
2,00153418,태광실업,,E,[첨부추가]사업보고서 (2018.12),20190329003459,태광실업,20190329,연
3,00340005,마이다스아이티,,E,[첨부추가]사업보고서 (2018.12),20190329001776,마이다스아이티,20190329,연
4,00530796,미성포리테크,094700,E,[첨부추가]사업보고서 (2018.12),20190329000118,미성포리테크,20190329,연
...,...,...,...,...,...,...,...,...,...
51,00409964,하이텍팜,106190,K,[기재정정]반기보고서 (2017.06),20190108000392,하이텍팜,20190108,
52,00409964,하이텍팜,106190,K,[기재정정]분기보고서 (2017.03),20190108000390,하이텍팜,20190108,
53,00660033,씨엔플러스,115530,K,[기재정정]반기보고서 (2018.06),20190104000332,씨엔플러스,20190104,
54,00273615,비케이탑스,030790,Y,[첨부정정]사업보고서 (2017.12),20190102000325,비케이탑스,20190102,연
55,01264234,엘에이티,311060,N,사업보고서 (2017.12),20190102000129,엘에이티,20190102,

### company(), company_by_name() - 기업개황

```python
# 기업의 개황정보를 읽어옵니다
dart.company(corp) 

# 기업을 검색하여 이름이 포함된 모든 기업들의 기업개황 정보를 반환합니다.
dart.company_by_name(name)
```

In [12]:
dart.company('005930') # 삼성전자, 005930, 00126380

{'status': '000',
 'message': '정상',
 'corp_code': '00126380',
 'corp_name': '삼성전자(주)',
 'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
 'stock_name': '삼성전자',
 'stock_code': '005930',
 'ceo_nm': '김기남, 김현석, 고동진',
 'corp_cls': 'Y',
 'jurir_no': '1301110006246',
 'bizr_no': '1248100998',
 'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
 'hm_url': 'www.sec.co.kr',
 'ir_url': '',
 'phn_no': '031-200-1114',
 'fax_no': '031-200-7538',
 'induty_code': '264',
 'est_dt': '19690113',
 'acc_mt': '12'}

find_company_by_name()는 기업을 검색하여 이름이 포함된 모든 기업들의 기업개황 정보를 반환합니다.

개별 회사의 corp_code(고유번호), stock_code (종목코드)를 얻는데도 유용하게 사용할 수 있습니다.

In [13]:
# 회사명에 삼성전자가 포함된 회사들에 대한 개황정보
data = dart.company_by_name('삼성전자')
data[:2]

[{'status': '000',
  'message': '정상',
  'corp_code': '01345812',
  'corp_name': '삼성전자서비스씨에스 주식회사',
  'corp_name_eng': 'SAMSUNG ELECTRONICS SERVICE CUSTOMER SATISFACTION., LTD.',
  'stock_name': '삼성전자서비스씨에스',
  'stock_code': '',
  'ceo_nm': '정석진',
  'corp_cls': 'E',
  'jurir_no': '1358110352541',
  'bizr_no': '7898701103',
  'adres': '경기도 수원시 영통구 중부대로 324 (매탄동, KT동수원지사)',
  'hm_url': '',
  'ir_url': '',
  'phn_no': '031-210-8938',
  'fax_no': '031-8006-1009',
  'induty_code': '75991',
  'est_dt': '20181105',
  'acc_mt': '12'},
 {'status': '000',
  'message': '정상',
  'corp_code': '00366997',
  'corp_name': '삼성전자로지텍(주)',
  'corp_name_eng': 'SELC.CO.,LTD',
  'stock_name': '삼성전자로지텍',
  'stock_code': '',
  'ceo_nm': '최윤범',
  'corp_cls': 'E',
  'jurir_no': '1301110046797',
  'bizr_no': '1248155381',
  'adres': '경기도 수원시 영통구 삼성로 129',
  'hm_url': 'www.selc.co.kr',
  'ir_url': '',
  'phn_no': '031-270-3485',
  'fax_no': '031-270-3673',
  'induty_code': '52999',
  'est_dt': '19980401',
  'acc_mt': '12'}]

가져온 기업개황 정보(dict list)를 데이터 프레임으로 가공하고, 필요한 컬럼을 지정하여 정리할 수 있습니다.

In [14]:
import pandas as pd

pd.DataFrame(data)[['stock_name' , 'stock_code' , 'ceo_nm' , 'corp_cls' , 'jurir_no' , 'bizr_no' , 'adres' ]]

,stock_name,stock_code,ceo_nm,corp_cls,jurir_no,bizr_no,adres
0,삼성전자서비스씨에스,,정석진,E,1358110352541,7898701103,"경기도 수원시 영통구 중부대로 324 (매탄동, KT동수원지사)"
1,삼성전자로지텍,,최윤범,E,1301110046797,1248155381,경기도 수원시 영통구 삼성로 129
2,삼성전자,005930,"김기남, 김현석, 고동진",Y,1301110006246,1248100998,경기도 수원시 영통구 삼성로 129 (매탄동)
3,삼성전자서비스,,심원환,E,1301110049139,1248158485,경기도 수원시 영통구 삼성로 290 (원천동)
4,삼성전자판매,,이평우,E,1801110210300,6178117517,경기도 성남시 분당구 황새울로 340

### document() - 공시서류 원문

In [15]:
# 삼성전자 사업보고서 (2018.12)
# http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20190401004781 
     
xml_text = dart.document('20190401004781') # 사업보고서 (2018.12)
xml_text[:2000]

'<?xml version="1.0" encoding="utf-8"?>\n\n\n<DOCUMENT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dart3.xsd">\n\n<DOCUMENT-HEADER AEXT-CLASS="Y">\n<DOCUMENT-NAME ACODE="11011">사업보고서</DOCUMENT-NAME>\n<FORMULA-VERSION ADATE="20190115">3.6</FORMULA-VERSION>\n<COMPANY-NAME AREGCIK="00126380">삼성전자</COMPANY-NAME>\n\n<SUMMARY>\n<EXTRACTION ACODE="LINK_FLAG" AFEATURE="BOTH">C</EXTRACTION>\n<EXTRACTION ACODE="FIN_TYPE" AFEATURE="BOTH">A</EXTRACTION>\n<EXTRACTION ACODE="CRP_RGS_NO_TEMP" AFEATURE="BOTH">130111-0006246</EXTRACTION>\n</SUMMARY>\n</DOCUMENT-HEADER>\n\n<BODY>\n\n<INSERTION ABASISNUMBER="SE1" AFREQUENCY="0" ADUPLICATION="N">\n<COMMENT>◆click◆ 정정문서 작성시 『정오표』 삽입</COMMENT>\n<LIBRARYLIST>정정신고(보고)-대표이사등의확인.LCommon</LIBRARYLIST>\n</INSERTION>\n\n<COVER>\n<P></P>\n<COVER-TITLE ATOC="Y" AASSOCNOTE="COVER">사 업 보 고 서</COVER-TITLE>\n<P>&cr;&cr;&cr;</P>\n<P USERMARK="F-16">                                    (제 50 기)</P>\n\n<TABLE-GROUP ACLASS="COVER" ADELETETABLE="N">\n\n<TABLE ACLASS="EXTRACTION" AFIXTABLE="Y" WIDTH="600" BORDER="0">\n\n<COLGROUP>\n<COL WIDTH="209"></COL>\n<COL WIDTH="153"></COL>\n<COL WIDTH="211"></COL>\n</COLGROUP>\n\n<TBODY>\n\n<TR ACOPY="N" ADELETE="N">\n<TD CLASS="NORMAL" ROWSPAN="2" ALIGN="RIGHT" VALIGN="MIDDLE" WIDTH="218" HEIGHT="60" AUPDATECONT="N">사업연도</TD>\n<TU CLASS="NORMAL" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="162" HEIGHT="30" AUNIT="PERIODFROM" AUNITVALUE="20180101">2018년 01월 01일</TU>\n<TD CLASS="NORMAL" VALIGN="MIDDLE" WIDTH="220" HEIGHT="30" AUPDATECONT="N"> 부터</TD>\n</TR>\n\n<TR ACOPY="N" ADELETE="N">\n<TU CLASS="NORMAL" ALIGN="CENTER" VALIGN="MIDDLE" WIDTH="162" HEIGHT="30" AUNIT="PERIODTO" AUNITVALUE="20181231">2018년 12월 31일</TU>\n<TD CLASS="NORMAL" VALIGN="MIDDLE" WIDTH="220" HEIGHT="30" AUPDATECONT="N"> 까지</TD>\n</TR>\n</TBODY>\n</TABLE>\n</TABLE-GROUP>\n<P></P>\n\n<TABLE AFIXTABLE="N" BORDER="0" WIDTH="600" ACLASS="NORMAL">\n\n<COLGROUP>\n<COL WIDTH="191"></COL>\n<COL WIDTH="391"></COL>\n</COLGROUP>\n\n<TBODY>\n\n<TR ACOPY="Y" ADELETE="Y">\n<TD WIDTH="200" HEIG'

### find_corp_code() - 고유번호 얻기
종목코드 혹은 기업명으로 고유번호를 가져옵니다.
전자공시에서 개별 기업은 고유번호로 식별 됩니다. 특히, 상장종목이 아닌 경우는 고유번호를 사용해야 합니다.

In [16]:
dart.find_corp_code('005930')

'00126380'

In [17]:
dart.find_corp_code('삼성전자')

'00126380'

### corp_codes - 고유번호(속성)
고유번호, 종목명, 종목코드 등의 정보를 포함하고 있는 속성값 입니다.  8만 1천여개 기업에 대한 고유번호, 종목명, 종목코드 등의 정보를 포함하고 있습니다.

In [18]:
dart.corp_codes

      corp_code          corp_name stock_code modify_date
0      00434003                 다코               20170630
1      00434456               일산약품               20170630
2      00430964              굿앤엘에스               20170630
3      00432403               한라판지               20170630
4      00388953  크레디피아제이십오차유동화전문회사               20170630
...         ...                ...        ...         ...
83312  01503577              비앤비레저               20200928
83313  01504293               파이런텍               20201007
83314  01504682          에이치디가양제일차               20201007
83315  01504691          에이치디가양제이차               20201007
83316  01504707          에이치디가양제삼차               20201007

[83317 rows x 4 columns]

## 2. 사업보고서

### report() - 사업보고서 주요정보
사업보고서의 주요 내용을 조회 합니다.

```python
dart.report(corp, key_word, bsns_year, reprt_code='11011')
```

`key_word`에 '증자','배당','자기주식','최대주주','최대주주변동','소액주주','임원','직원','임원개인보수','임원전체보수','개인별보수','타법인출자' 중의 하나를 지정할 수 있습니다.

bsns_year 에 사업 년도를 지정합니다 (문자열 혹은 정수값)

함수에 대한 더 상세한 내용은 [OpenDartReader - Reference Manual]을 참고하십시오.

In [19]:
# 삼성전자(005930), 배당관련 사항, 2018년
dart.report('005930', '배당', 2018)

,rcept_no,corp_cls,corp_code,corp_name,se,thstrm,frmtrm,lwfr,stock_knd
0,20190401004781,Y,00126380,삼성전자,주당액면가액(원),100,"5,000","5,000",NaN
1,20190401004781,Y,00126380,삼성전자,(연결)당기순이익(백만원),"43,890,877","41,344,569","22,415,655",NaN
2,20190401004781,Y,00126380,삼성전자,(별도)당기순이익(백만원),"32,815,127","28,800,837","11,579,749",NaN
3,20190401004781,Y,00126380,삼성전자,(연결)주당순이익(원),"6,461","299,868","157,967",NaN
4,20190401004781,Y,00126380,삼성전자,현금배당금총액(백만원),"9,619,243","5,826,302","3,991,892",NaN
5,20190401004781,Y,00126380,삼성전자,주식배당금총액(백만원),-,-,-,NaN
6,20190401004781,Y,00126380,삼성전자,(연결)현금배당성향(%),21.90,14.10,17.80,NaN
7,20190401004781,Y,00126380,삼성전자,현금배당수익률(%),3.70,1.70,1.60,보통주
8,20190401004781,Y,00126380,삼성전자,현금배당수익률(%),4.50,2.10,2.00,우선주
9,20190401004781,Y,00126380,삼성전자,주식배당수익률(%),-,-,-,보통주
10,20190401004781,Y,00126380,삼성전자,주식배당수익률(%),-,-,-,우선주
11,20190401004781,Y,00126380,삼성전자,주당 현금배당금(원),"1,416","42,500","28,500",보통주
12,20190401004781,Y,00126380,삼성전자,주당 현금배당금(원),"1,417","42,550","28,550",우선주
13,20190401004781,Y,00126380,삼성전자,주당 주식배당(주),-,-,-,보통주
14,20190401004781,Y,00126380,삼성전자,주당 주식배당(주),-,-,-,우선주

In [20]:
# 서울반도체(046890), 최대주주 관한 사항, 2018년

dart.report('046890', '최대주주', 2018)

,rcept_no,corp_cls,corp_code,corp_name,stock_knd,rm,nm,relate,bsis_posesn_stock_co,bsis_posesn_stock_qota_rt,trmend_posesn_stock_co,trmend_posesn_stock_qota_rt
0,20190401003450,K,00130763,서울반도체,보통주,-,이정훈,본인,"9,749,744",16.72,"9,749,744",16.72
1,20190401003450,K,00130763,서울반도체,보통주,-,이민호,특수관계인,"5,076,358",8.71,"5,076,358",8.71
2,20190401003450,K,00130763,서울반도체,보통주,-,이민규,특수관계인,"5,076,358",8.71,"5,076,358",8.71
3,20190401003450,K,00130763,서울반도체,보통주,-,계,NaN,"19,902,460",34.13,"19,902,460",34.13
4,20190401003450,K,00130763,서울반도체,-,-,계,NaN,-,-,-,-

In [21]:
# 서울반도체(046890), 임원 관한 사항, 2018년

dart.report('046890', '임원', 2018)

,rcept_no,corp_cls,corp_code,corp_name,nm,sexdstn,birth_ym,ofcps,rgist_exctv_at,fte_at,chrg_job,main_career,mxmm_shrholdr_relate,hffc_pd,tenure_end_on
0,20190401003450,K,00130763,서울반도체,이정훈,남,1953년 01월,대표이사\n 사장,등기임원,상근,경영총괄,- 삼신전기(주) 부사장\n- 서울반도체(주) 대표이사(現),본인,1992년~,2019년 03월 28일
1,20190401003450,K,00130763,서울반도체,박형건,남,1960년 04월,사외이사,등기임원,비상근,사외이사/\n 감사위원,- 연세대경영학학사/서울대경영학석사수료\n- 국세청 정보공개심의위원회 위원\n- 우...,-,2016년~,2020년 03월 27일
2,20190401003450,K,00130763,서울반도체,장정식,남,1955년 07월,사외이사,등기임원,비상근,사외이사/\n 감사위원,- 서울대 공업화학과 학사/석사\n- Case Western Reserve 대학 공...,-,2018년~,2020년 03월 27일
3,20190401003450,K,00130763,서울반도체,오명민,남,1977년 01월,사외이사,등기임원,비상근,사외이사/\n 감사위원,- 서울대 원예학과 학사/석사\n- Kansas 주립대학 원예학과 박사\n- 충북대...,-,2018년~,2020년 03월 27일

In [22]:
# 서울반도체(046890), 직원 관한 사항, 2018년

dart.report('046890', '직원', 2018)

,rcept_no,corp_cls,corp_code,corp_name,rm,sexdstn,fo_bbm,reform_bfe_emp_co_rgllbr,reform_bfe_emp_co_cnttk,reform_bfe_emp_co_etc,rgllbr_co,rgllbr_abacpt_labrr_co,cnttk_co,cnttk_abacpt_labrr_co,sm,avrg_cnwk_sdytrn,fyer_salary_totamt,jan_salary_am
0,20190401003450,K,00130763,서울반도체,-,남,관리사무직,-,-,-,471,-,35,-,506,6.3,"42,571,000,000","84,000,000"
1,20190401003450,K,00130763,서울반도체,-,여,관리사무직,-,-,-,124,-,11,-,135,5.6,"6,952,000,000","52,000,000"
2,20190401003450,K,00130763,서울반도체,-,남,생산직,-,-,-,247,-,34,-,281,3.6,"13,254,000,000","47,000,000"
3,20190401003450,K,00130763,서울반도체,-,여,생산직,-,-,-,118,-,12,-,130,6.3,"6,092,000,000","47,000,000"

## 3. 상장기업 재무정보

In [23]:
# 삼성전자 2018 재무제표

dart.finstate('삼성전자', 2018) # 사업보고서

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,thstrm_nm,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_dt,bfefrmtrm_amount,ord
0,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동자산,제 50 기,2018.12.31 현재,"174,697,424,000,000",제 49 기,2017.12.31 현재,"146,982,464,000,000",제 48 기,2016.12.31 현재,"141,429,704,000,000",1
1,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동자산,제 50 기,2018.12.31 현재,"164,659,820,000,000",제 49 기,2017.12.31 현재,"154,769,626,000,000",제 48 기,2016.12.31 현재,"120,744,620,000,000",3
2,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,자산총계,제 50 기,2018.12.31 현재,"339,357,244,000,000",제 49 기,2017.12.31 현재,"301,752,090,000,000",제 48 기,2016.12.31 현재,"262,174,324,000,000",5
3,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동부채,제 50 기,2018.12.31 현재,"69,081,510,000,000",제 49 기,2017.12.31 현재,"67,175,114,000,000",제 48 기,2016.12.31 현재,"54,704,095,000,000",7
4,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동부채,제 50 기,2018.12.31 현재,"22,522,557,000,000",제 49 기,2017.12.31 현재,"20,085,548,000,000",제 48 기,2016.12.31 현재,"14,507,196,000,000",9
5,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,부채총계,제 50 기,2018.12.31 현재,"91,604,067,000,000",제 49 기,2017.12.31 현재,"87,260,662,000,000",제 48 기,2016.12.31 현재,"69,211,291,000,000",11
6,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본금,제 50 기,2018.12.31 현재,"897,514,000,000",제 49 기,2017.12.31 현재,"897,514,000,000",제 48 기,2016.12.31 현재,"897,514,000,000",13
7,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,이익잉여금,제 50 기,2018.12.31 현재,"242,698,956,000,000",제 49 기,2017.12.31 현재,"215,811,200,000,000",제 48 기,2016.12.31 현재,"193,086,317,000,000",17
8,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본총계,제 50 기,2018.12.31 현재,"247,753,177,000,000",제 49 기,2017.12.31 현재,"214,491,428,000,000",제 48 기,2016.12.31 현재,"192,963,033,000,000",21
9,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,매출액,제 50 기,2018.01.01 ~ 2018.12.31,"243,771,415,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"239,575,376,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"201,866,745,000,000",23
10,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,영업이익,제 50 기,2018.01.01 ~ 2018.12.31,"58,886,669,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"53,645,038,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"29,240,672,000,000",25
11,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,법인세차감전 순이익,제 50 기,2018.01.01 ~ 2018.12.31,"61,159,958,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"56,195,967,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"30,713,652,000,000",27
12,20190401004781,11011,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,당기순이익,제 50 기,2018.01.01 ~ 2018.12.31,"44,344,857,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"42,186,747,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"22,726,092,000,000",29
13,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,유동자산,제 50 기,2018.12.31 현재,"80,039,455,000,000",제 49 기,2017.12.31 현재,"70,155,189,000,000",제 48 기,2016.12.31 현재,"69,981,128,000,000",2
14,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,비유동자산,제 50 기,2018.12.31 현재,"138,981,902,000,000",제 49 기,2017.12.31 현재,"128,086,171,000,000",제 48 기,2016.12.31 현재,"104,821,831,000,000",4
15,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,자산총계,제 50 기,2018.12.31 현재,"219,021,357,000,000",제 49 기,2017.12.31 현재,"198,241,360,000,000",제 48 기,2016.12.31 현재,"174,802,959,000,000",6
16,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,유동부채,제 50 기,2018.12.31 현재,"43,145,053,000,000",제 49 기,2017.12.31 현재,"44,495,084,000,000",제 48 기,2016.12.31 현재,"34,076,122,000,000",8
17,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,비유동부채,제 50 기,2018.12.31 현재,"2,888,179,000,000",제 49 기,2017.12.31 현재,"2,176,501,000,000",제 48 기,2016.12.31 현재,"3,180,075,000,000",10
18,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,부채총계,제 50 기,2018.12.31 현재,"46,033,232,000,000",제 49 기,2017.12.31 현재,"46,671,585,000,000",제 48 기,2016.12.31 현재,"37,256,197,000,000",12
19,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,자본금,제 50 기,2018.12.31 현재,"897,514,000,000",제 49 기,2017.12.31 현재,"897,514,000,000",제 48 기,2016.12.31 현재,"897,514,000,000",15
20,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,이익잉여금,제 50 기,2018.12.31 현재,"166,555,532,000,000",제 49 기,2017.12.31 현재,"150,928,724,000,000",제 48 기,2016.12.31 현재,"140,747,574,000,000",19
21,20190401004781,11011,2018,00126380,005930,OFS,재무제표,BS,재무상태표,자본총계,제 50 기,2018.12.31 현재,"172,988,125,000,000",제 49 기,2017.12.31 현재,"151,569,775,000,000",제 48 기,2016.12.31 현재,"137,546,762,000,000",22
22,20190401004781,11011,2018,00126380,005930,OFS,재무제표,IS,손익계산서,매출액,제 50 기,2018.01.01 ~ 2018.12.31,"170,381,870,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"161,915,007,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"133,947,204,000,000",24
23,20190401004781,11011,2018,00126380,005930,OFS,재무제표,IS,손익계산서,영업이익,제 50 기,2018.01.01 ~ 2018.12.31,"43,699,451,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"34,857,091,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"13,647,436,000,000",26
24,20190401004781,11011,2018,00126380,005930,OFS,재무제표,IS,손익계산서,법인세차감전 순이익,제 50 기,2018.01.01 ~ 2018.12.31,"44,398,855,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"36,533,552,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"14,725,074,000,000",28
25,20190401004781,11011,2018,00126380,005930,OFS,재무제표,IS,손익계산서,당기순이익,제 50 기,2018.01.01 ~ 2018.12.31,"32,815,127,000,000",제 49 기,2017.01.01 ~ 2017.12.31,"28,800,837,000,000",제 48 기,2016.01.01 ~ 2016.12.31,"11,579,749,000,000",30

In [24]:
# 삼성전자 2018Q1 재무제표

dart.finstate('삼성전자', 2018, reprt_code='11013') # 2018년 1분기 보고서 재무제표

,rcept_no,reprt_code,bsns_year,corp_code,stock_code,fs_div,fs_nm,sj_div,sj_nm,account_nm,thstrm_nm,thstrm_dt,thstrm_amount,frmtrm_nm,frmtrm_dt,frmtrm_amount,ord,thstrm_add_amount,frmtrm_add_amount
0,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동자산,제 50 기1분기말,2018.03.31 현재,"154,941,953,000,000",제 49 기말,2017.12.31 현재,"146,982,464,000,000",1,NaN,NaN
1,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동자산,제 50 기1분기말,2018.03.31 현재,"157,531,160,000,000",제 49 기말,2017.12.31 현재,"154,769,626,000,000",3,NaN,NaN
2,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,자산총계,제 50 기1분기말,2018.03.31 현재,"312,473,113,000,000",제 49 기말,2017.12.31 현재,"301,752,090,000,000",5,NaN,NaN
3,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,유동부채,제 50 기1분기말,2018.03.31 현재,"68,298,586,000,000",제 49 기말,2017.12.31 현재,"67,175,114,000,000",7,NaN,NaN
4,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,비유동부채,제 50 기1분기말,2018.03.31 현재,"20,914,647,000,000",제 49 기말,2017.12.31 현재,"20,085,548,000,000",9,NaN,NaN
5,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,부채총계,제 50 기1분기말,2018.03.31 현재,"89,213,233,000,000",제 49 기말,2017.12.31 현재,"87,260,662,000,000",11,NaN,NaN
6,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본금,제 50 기1분기말,2018.03.31 현재,"897,514,000,000",제 49 기말,2017.12.31 현재,"897,514,000,000",13,NaN,NaN
7,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,이익잉여금,제 50 기1분기말,2018.03.31 현재,"222,485,398,000,000",제 49 기말,2017.12.31 현재,"215,811,200,000,000",17,NaN,NaN
8,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,BS,재무상태표,자본총계,제 50 기1분기말,2018.03.31 현재,"223,259,880,000,000",제 49 기말,2017.12.31 현재,"214,491,428,000,000",21,NaN,NaN
9,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,매출액,제 50 기1분기,2018.01.01 ~ 2018.03.31,"60,563,714,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"50,547,526,000,000",23,"60,563,714,000,000","50,547,526,000,000"
10,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,영업이익,제 50 기1분기,2018.01.01 ~ 2018.03.31,"15,642,170,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"9,898,361,000,000",25,"15,642,170,000,000","9,898,361,000,000"
11,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,법인세차감전 순이익,제 50 기1분기,2018.01.01 ~ 2018.03.31,"16,175,907,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"10,164,576,000,000",27,"16,175,907,000,000","10,164,576,000,000"
12,20180515001699,11013,2018,00126380,005930,CFS,연결재무제표,IS,손익계산서,당기순이익,제 50 기1분기,2018.01.01 ~ 2018.03.31,"11,688,544,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"7,684,354,000,000",29,"11,688,544,000,000","7,684,354,000,000"
13,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,유동자산,제 50 기1분기말,2018.03.31 현재,"72,370,085,000,000",제 49 기말,2017.12.31 현재,"70,155,189,000,000",2,NaN,NaN
14,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,비유동자산,제 50 기1분기말,2018.03.31 현재,"132,836,079,000,000",제 49 기말,2017.12.31 현재,"128,086,171,000,000",4,NaN,NaN
15,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,자산총계,제 50 기1분기말,2018.03.31 현재,"205,206,164,000,000",제 49 기말,2017.12.31 현재,"198,241,360,000,000",6,NaN,NaN
16,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,유동부채,제 50 기1분기말,2018.03.31 현재,"47,168,741,000,000",제 49 기말,2017.12.31 현재,"44,495,084,000,000",8,NaN,NaN
17,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,비유동부채,제 50 기1분기말,2018.03.31 현재,"1,842,051,000,000",제 49 기말,2017.12.31 현재,"2,176,501,000,000",10,NaN,NaN
18,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,부채총계,제 50 기1분기말,2018.03.31 현재,"49,010,792,000,000",제 49 기말,2017.12.31 현재,"46,671,585,000,000",12,NaN,NaN
19,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,자본금,제 50 기1분기말,2018.03.31 현재,"897,514,000,000",제 49 기말,2017.12.31 현재,"897,514,000,000",15,NaN,NaN
20,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,이익잉여금,제 50 기1분기말,2018.03.31 현재,"154,284,538,000,000",제 49 기말,2017.12.31 현재,"150,928,724,000,000",19,NaN,NaN
21,20180515001699,11013,2018,00126380,005930,OFS,재무제표,BS,재무상태표,자본총계,제 50 기1분기말,2018.03.31 현재,"156,195,372,000,000",제 49 기말,2017.12.31 현재,"151,569,775,000,000",22,NaN,NaN
22,20180515001699,11013,2018,00126380,005930,OFS,재무제표,IS,손익계산서,매출액,제 50 기1분기,2018.01.01 ~ 2018.03.31,"42,606,978,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"34,578,524,000,000",24,"42,606,978,000,000","34,578,524,000,000"
23,20180515001699,11013,2018,00126380,005930,OFS,재무제표,IS,손익계산서,영업이익,제 50 기1분기,2018.01.01 ~ 2018.03.31,"11,200,897,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"5,675,571,000,000",26,"11,200,897,000,000","5,675,571,000,000"
24,20180515001699,11013,2018,00126380,005930,OFS,재무제표,IS,손익계산서,법인세차감전 순이익,제 50 기1분기,2018.01.01 ~ 2018.03.31,"11,568,977,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"6,309,744,000,000",28,"11,568,977,000,000","6,309,744,000,000"
25,20180515001699,11013,2018,00126380,005930,OFS,재무제표,IS,손익계산서,당기순이익,제 50 기1분기,2018.01.01 ~ 2018.03.31,"8,452,458,000,000",제 49 기1분기,2017.01.01 ~ 2017.03.31,"4,873,767,000,000",30,"8,452,458,000,000","4,873,767,000,000"

## 4. 지분공시
* major_shareholders() - 대량보유 상황보고
* major_shareholders_exec() - 임원ㆍ주요주주 소유보고

In [25]:
dart.major_shareholders('삼성전자') # 종목코드, 종목명, 고유번호 모두 가능

,rcept_no,rcept_dt,corp_code,corp_name,report_tp,repror,stkqy,stkqy_irds,stkrt,stkrt_irds,ctr_stkqy,ctr_stkrt,report_resn
0,20190207000145,2019-02-07,00126380,삼성전자,약식,BlackRockFundAdvisors,"300,391,061","2,108,161",5.03,0.04,-,-,- 단순투자목적으로 장내에서 주식 매수
1,20190425000475,2019-04-25,00126380,삼성전자,일반,삼성물산,"1,266,296,034","-2,384,443",21.21,-0.04,-,-,특별관계자 및 보유주식수 변동
2,20200207000636,2020-02-07,00126380,삼성전자,약식,국민연금공단,"638,070,003","37,907,275",10.69,0.64,-,-,단순투자목적에서 일반투자목적으로 보유목적 변경
3,20200325001033,2020-03-25,00126380,삼성전자,일반,삼성물산,"1,266,621,769","325,735",21.22,0.01,-,-,특별관계자 및 보유주식수 변동

In [26]:
dart.major_shareholders_exec('삼성전자') # 종목코드, 종목명, 고유번호 모두 가능

,rcept_no,rcept_dt,corp_code,corp_name,repror,isu_exctv_rgist_at,isu_exctv_ofcps,isu_main_shrholdr,sp_stock_lmp_cnt,sp_stock_lmp_irds_cnt,sp_stock_lmp_rate,sp_stock_lmp_irds_rate
0,20190116000364,2019-01-16,00126380,삼성전자,엄대현,비등기임원,부사장,-,"25,000","25,000",0.00,0.00
1,20190125000514,2019-01-25,00126380,삼성전자,양걸,비등기임원,부사장,-,"1,400","1,400",0.00,0.00
2,20190129000254,2019-01-29,00126380,삼성전자,국민연금공단,-,-,10%이상주주,"608,486,033","608,486,033",8.96,8.96
3,20190208000342,2019-02-08,00126380,삼성전자,국민연금공단,-,-,10%이상주주,"607,706,922","-779,111",8.95,-0.01
4,20190211000454,2019-02-11,00126380,삼성전자,조상호,비등기임원,전무,-,"1,834","-19,166",0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
167,20210105000198,2021-01-05,00126380,삼성전자,엄대현,비등기임원,부사장,-,"11,000","-4,000",0.00,0.00
168,20210105000353,2021-01-05,00126380,삼성전자,전승준,비등기임원,전무,-,"12,000","-2,200",0.00,0.00
169,20210105000430,2021-01-05,00126380,삼성전자,이상훈,비등기임원,사장,-,"11,000","-1,000",0.00,0.00
170,20210107000257,2021-01-07,00126380,삼성전자,국민연금공단,-,-,10%이상주주,"647,187,613","-7,290,212",9.53,-0.11
171,20210111000382,2021-01-11,00126380,삼성전자,안규리,등기임원,사외이사,-,"2,700",100,0.00,0.00

## 5. 확장기능
Open DART의 API가 제공하지 않는 유용한 확장 기능을 제공합니다.

In [27]:
# 지정한 날짜의 공시목록 전체 (시간 정보 포함)

dart.list_date_ex('2020-01-03')

,rcept_dt,corp_cls,corp_code,corp_name,rcept_no,report_nm,flr_nm,rm
0,2020-01-03 18:40:00,유가증권,00155355,풀무원,20200103800678,장래사업ㆍ경영계획(공정공시),풀무원,한국거래소 유가증권시장본부
1,2020-01-03 18:26:00,코스닥,00475718,이엠앤아이,20200103000641,[기재정정]주요사항보고서(감자결정),이엠앤아이,정정신고
2,2020-01-03 18:25:00,코스닥,00475718,이엠앤아이,20200103000648,[기재정정]주요사항보고서(유상증자결정),이엠앤아이,정정신고
3,2020-01-03 18:25:00,코스닥,00475718,이엠앤아이,20200103000645,[기재정정]주요사항보고서(유상증자결정),이엠앤아이,정정신고
4,2020-01-03 18:20:00,코넥스,00978075,옐로페이,20200103600668,거래처와의거래중단,옐로페이,본 문서는 한국거래소 코넥스시장
...,...,...,...,...,...,...,...,...
76,2020-01-03 07:30:00,기타법인,01005710,동원관광개발,20200102000464,감사보고서 (2019.09),예교지성회계법인,
77,2020-01-03 07:30:00,코스닥,00612489,아이쓰리시스템,20200102000459,임원ㆍ주요주주특정증권등소유상황보고서,김병혁,
78,2020-01-03 07:30:00,코스닥,00592653,유비벨록스,20200102000460,주식등의대량보유상황보고서(일반),이흥복,
79,2020-01-03 07:30:00,코스닥,00812362,포티스,20200102000465,[기재정정]주주총회소집공고,포티스,정정신고
80,2020-01-03 07:30:00,코스닥,00812362,포티스,20200102000466,[기재정정]참고서류,포티스,정정신고

보고서의 개별 문서(sub_docs)와 첨부 문서(attach_doc_list), 첨부 파일(attach_file_list)에 대한 목록을 가져옵니다.

In [28]:
rcp_no = '20190401004781' # 삼성전자 2018년 사업보고서

In [29]:
# 개별 문서 제목과 URL
dart.sub_docs(rcp_no)[:10]

            title                                                url
0       사 업 보 고 서  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
1  【 대표이사 등의 확인 】  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
2       I. 회사의 개요  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
3       1. 회사의 개요  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
4       2. 회사의 연혁  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
5     3. 자본금 변동사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
6     4. 주식의 총수 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
7       5. 의결권 현황  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
8  6. 배당에 관한 사항 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
9      II. 사업의 내용  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...

In [30]:
# 첨부 문서 제목과 URL
dart.attach_doc_list(rcp_no)

,title,url
0,2019.04.01 감사보고서,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
1,2019.04.01 감사의감사보고서,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
2,2019.04.01 내부감시장치에대한감사의의견서,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
3,2019.04.01 내부회계관리제도운영보고서,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
4,2019.04.01 연결감사보고서,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
5,2019.04.01 영업보고서,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
6,2019.04.01 정관,http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...

In [31]:
# 첨부 파일 제목과 URL
dart.attach_file_list(rcp_no)

,file_name,url,type
0,[삼성전자]사업보고서(2019.04.01).pdf,http://dart.fss.or.kr/pdf/download/pdf.do?rcp_...,pdf
1,50기 사업보고서 대표이사 등의 확인서(국문).jpg,http://dart.fss.or.kr/pdf/download/file.do?rcp...,file
2,연구조직도.jpg,http://dart.fss.or.kr/pdf/download/file.do?rcp...,file
3,[삼성전자]사업보고서_재무제표(2019.04.01)_ko.xls,http://dart.fss.or.kr/pdf/download/excel.do?rc...,excel
4,[삼성전자]사업보고서_IFRS(원문XBRL)(2019.04.01).zip,http://dart.fss.or.kr/pdf/download/ifrs.do?rcp...,ifrs

In [32]:
# 삼성전자 2018년 사업보고서
attaches = dart.attach_file_list('20190401004781')
attaches

,file_name,url,type
0,[삼성전자]사업보고서(2019.04.01).pdf,http://dart.fss.or.kr/pdf/download/pdf.do?rcp_...,pdf
1,50기 사업보고서 대표이사 등의 확인서(국문).jpg,http://dart.fss.or.kr/pdf/download/file.do?rcp...,file
2,연구조직도.jpg,http://dart.fss.or.kr/pdf/download/file.do?rcp...,file
3,[삼성전자]사업보고서_재무제표(2019.04.01)_ko.xls,http://dart.fss.or.kr/pdf/download/excel.do?rc...,excel
4,[삼성전자]사업보고서_IFRS(원문XBRL)(2019.04.01).zip,http://dart.fss.or.kr/pdf/download/ifrs.do?rcp...,ifrs

In [33]:
xls_url = attaches.loc[attaches['type']=='excel', 'url'].values[0] # 첨부 재무제표 엑셀
xls_url

'http://dart.fss.or.kr/pdf/download/excel.do?rcp_no=20190401004781&dcm_no=6616741&lang=ko'

In [34]:
dart.retrieve(xls_url, '삼성전자_2018.xls')

'삼성전자_2018.xls'

In [38]:
import pandas as pd

xl = pd.ExcelFile('삼성전자_2018.xls')
xl.sheet_names

['기본정보',
 '연결 재무상태표',
 '연결 손익계산서',
 '연결 포괄손익계산서',
 '연결 자본변동표',
 '연결 현금흐름표',
 '재무상태표',
 '손익계산서',
 '포괄손익계산서',
 '자본변동표',
 '현금흐름표']

In [39]:
pd.read_excel('삼성전자_2018.xls', sheet_name='연결 손익계산서', skiprows=6)

                                       제 50 기     제 49 기     제 48 기
0                          수익(매출액)  243771415  239575376  201866745
1                             매출원가  132394411  129290661  120277715
2                            매출총이익  111377004  110284715   81589030
3                          판매비와관리비   52490335   56639677   52348358
4                         영업이익(손실)   58886669   53645038   29240672
5                             기타수익    1485037    3010657    3238261
6                             기타비용    1142018    1419648    2463814
7                            지분법이익     539845     201442      19501
8                             금융수익    9999321    9737391   11385645
9                             금융비용    8608896    8978913   10706613
10                 법인세비용차감전순이익(손실)   61159958   56195967   30713652
11                           법인세비용   16815101   14009220    7987560
12                      계속영업이익(손실)   44344857   42186747   22726092
13                       당기순이익(손실)   44344857   42186747   22726092
14                   당기순이익(손실)의 귀속
15      지배기업의 소유주에게 귀속되는 당기순이익(손실)   43890877   41344569   22415655
16           비지배지분에 귀속되는 당기순이익(손실)     453980     842178     310437
17                            주당이익
18             기본주당이익(손실) (단위 : 원)       6461       5997       3159
19             희석주당이익(손실) (단위 : 원)       6461       5997       3159

#### 2021  [FinanceData.KR](http://financedata.kr) | [facebook.com/financedata](http://facebook.com/financedata)